"""Render the main 5-baseline multi-scenario presentation video.

This video intentionally uses only the defensible main comparison columns:

- CV baseline
- PointNav/DD-PPO endpoint oracle
- A* pose-graph oracle
- GT
- Ours

It concatenates two GT sources in one sequence:

1. Human-action replay block: GT is generated by replaying public human action
   labels in ViZDoom.
2. V4 multi-scenario block: GT is the recorded WIT-VZ ViZDoom trajectory from
   multiple scenarios.

PointNav and A* are privileged upper-bound baselines: they receive the GT future
endpoint, and A* also uses a recorded pose graph.
"""

from __future__ import annotations

import argparse
import json
import math
import sys
from pathlib import Path
from typing import Any, Iterable

import cv2
import numpy as np
import torch
from PIL import Image, ImageDraw

SCRIPT_DIR = Path(__file__).resolve().parent
ROOT = SCRIPT_DIR.parent
if str(SCRIPT_DIR) not in sys.path:
    sys.path.insert(0, str(SCRIPT_DIR))
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from render_triptych_demo_video import (  # noqa: E402
    BG_COLOR,
    CV_COLOR,
    GT_COLOR,
    MUTED_COLOR,
    PRED_COLOR,
    TEXT_COLOR,
    axis_scale,
    clipped_path,
    draw_path_plot,
    font,
    load_raw_dirs,
    load_rgb,
    metadata_label,
    moving_frame_paths,
    paste_center,
    path_error,
    read_json,
    read_jsonl,
    resolve_frame_path,
    wrap,
)
from src.models.motion import constant_velocity_path  # noqa: E402
from src.models.navigation_oracles import (  # noqa: E402
    PoseGraphAStarPlanner,
    astar_oracle_prediction,
    pointnav_goal_oracle_prediction,
)
from src.wit_vz.io import load_json  # noqa: E402


POINTNAV_COLOR = (99, 90, 190)
ASTAR_COLOR = (34, 139, 150)
HUMAN_BLOCK_COLOR = (142, 82, 22)
V4_BLOCK_COLOR = (44, 101, 88)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--human-dataset", type=Path, default=Path("data/wit_vz/processed/wit_vz_sauerkrautlm_human_replay_001"))
    parser.add_argument(
        "--human-ours-predictions",
        type=Path,
        default=Path("reports/demo/human_action_replay_gt_comparison_05s/eval_test/predictions.jsonl"),
    )
    parser.add_argument(
        "--human-summary",
        type=Path,
        default=Path("reports/demo/human_action_replay_gt_comparison_05s/summary.json"),
    )
    parser.add_argument("--human-max-samples", type=int, default=3)
    parser.add_argument("--v4-dataset", type=Path, default=Path("data/wit_vz/processed/horizon_sweep_v4_defaults/future_05s"))
    parser.add_argument(
        "--v4-ours-predictions",
        type=Path,
        default=Path("runs/horizon_sweep_v4_defaults/dinov3_timesformer_single_05s/predictions.jsonl"),
    )
    parser.add_argument(
        "--v4-oracle-predictions",
        type=Path,
        default=Path("outputs/navigation_oracle_baselines_v4/predictions_05s.jsonl"),
    )
    parser.add_argument("--v4-max-samples", type=int, default=9)
    parser.add_argument("--min-target-extent", type=float, default=20.0)
    parser.add_argument("--astar-cell-size", type=float, default=16.0)
    parser.add_argument("--report-dir", type=Path, default=Path("reports/demo/main_5baseline_multiscenario_05s"))
    parser.add_argument(
        "--output",
        type=Path,
        default=Path("reports/demo/presentation_sequence/demo_main_5baseline_multiscenario_05s.mp4"),
    )
    parser.add_argument("--width", type=int, default=2560)
    parser.add_argument("--height", type=int, default=1440)
    parser.add_argument("--fps", type=int, default=8)
    parser.add_argument("--hold-last-frames", type=int, default=8)
    parser.add_argument("--max-frames-per-item", type=int, default=0)
    parser.add_argument("--raw-root-base", action="append", default=[])
    return parser.parse_args()


def average_prediction_rows(path: Path) -> dict[str, dict[str, Any]]:
    grouped: dict[str, list[dict[str, Any]]] = {}
    for row in read_jsonl(path):
        grouped.setdefault(str(row["sample_id"]), []).append(row)
    averaged: dict[str, dict[str, Any]] = {}
    for sample_id, rows in grouped.items():
        if len(rows) == 1:
            averaged[sample_id] = rows[0]
            continue
        first = dict(rows[0])
        predictions = [torch.tensor(row["prediction"], dtype=torch.float32) for row in rows if "prediction" in row]
        if predictions:
            first["prediction"] = torch.stack(predictions, dim=0).mean(dim=0).tolist()
        if "target" in first:
            target = torch.tensor(first["target"], dtype=torch.float32)
            pred = torch.tensor(first["prediction"], dtype=torch.float32)
            distances = torch.linalg.norm(pred - target, dim=-1)
            first["ADE"] = float(distances.mean().item())
            first["FDE"] = float(distances[-1].item())
        averaged[sample_id] = first
    return averaged


def metric_mean(rows: Iterable[dict[str, Any]], key: str) -> float:
    values = [float(row[key]) for row in rows if key in row]
    return float(sum(values) / max(len(values), 1))


def split_ids(dataset: Path, split: str = "test") -> set[str]:
    splits = load_json(dataset / "splits.json")
    return set(str(item) for item in splits.get(split, []))


def selected_human_ids(summary: Path, max_samples: int) -> list[tuple[str, str]]:
    data = read_json(summary)
    rows = data if isinstance(data, list) else data.get("selected", [])
    priority = [
        "easy",
        "CV-hard / ours better",
        "ours worse than CV",
        "long rollout",
        "hard",
    ]
    scored = []
    for row in rows:
        case = str(row.get("case", "selected"))
        sample_id = str(row.get("sample_id", ""))
        if not sample_id:
            continue
        rank = priority.index(case) if case in priority else len(priority)
        scored.append((rank, sample_id, case))
    scored.sort(key=lambda item: item[0])
    return [(sample_id, case) for _, sample_id, case in scored[:max_samples]]


def make_oracle_row(
    sample: dict[str, Any],
    target: list[list[float]],
    prediction: list[list[float]],
    cv_path: list[list[float]] | None,
    planner: PoseGraphAStarPlanner,
) -> dict[str, Any]:
    batch = {
        "sample_id": [sample["sample_id"]],
        "ego_history": torch.tensor([sample["relative_egomotion_history"]], dtype=torch.float32),
        "future_path": torch.tensor([target], dtype=torch.float32),
        "current_pose": [sample["current_pose"]],
        "metadata": [sample.get("metadata", {})],
        "source": [sample.get("source", {})],
    }
    if not cv_path:
        cv_path = constant_velocity_path(batch["ego_history"], len(target))[0].cpu().tolist()
    pointnav_path = pointnav_goal_oracle_prediction(batch)[0].cpu().tolist()
    astar_path = astar_oracle_prediction(sample, planner)
    horizon = min(len(target), len(prediction), len(cv_path), len(pointnav_path), len(astar_path))
    target = target[:horizon]
    prediction = prediction[:horizon]
    cv_path = cv_path[:horizon]
    pointnav_path = pointnav_path[:horizon]
    astar_path = astar_path[:horizon]
    cv_ade, cv_fde = path_error(cv_path, target)
    pointnav_ade, pointnav_fde = path_error(pointnav_path, target)
    astar_ade, astar_fde = path_error(astar_path, target)
    ours_ade, ours_fde = path_error(prediction, target)
    return {
        "sample_id": sample["sample_id"],
        "target": target,
        "prediction": prediction,
        "cv": cv_path,
        "pointnav": pointnav_path,
        "astar": astar_path,
        "cv_ADE": cv_ade,
        "cv_FDE": cv_fde,
        "pointnav_ADE": pointnav_ade,
        "pointnav_FDE": pointnav_fde,
        "astar_ADE": astar_ade,
        "astar_FDE": astar_fde,
        "ours_ADE": ours_ade,
        "ours_FDE": ours_fde,
    }


def build_human_items(args: argparse.Namespace, bases: list[Path]) -> tuple[list[dict[str, Any]], dict[str, Any]]:
    samples = {str(row["sample_id"]): row for row in read_jsonl(args.human_dataset / "samples.jsonl")}
    ours = average_prediction_rows(args.human_ours_predictions)
    raw_dirs = load_raw_dirs(args.human_dataset, bases)
    planner = PoseGraphAStarPlanner.from_samples(samples.values(), cell_size=args.astar_cell_size)
    items: list[dict[str, Any]] = []
    rows_for_metrics: list[dict[str, Any]] = []

    for sample_id in split_ids(args.human_dataset):
        sample = samples.get(sample_id)
        pred_row = ours.get(sample_id)
        if sample is None or pred_row is None:
            continue
        target = pred_row.get("target") or sample.get("future_local_path") or []
        prediction = pred_row.get("prediction") or []
        cv_path = pred_row.get("constant_velocity_prediction")
        if not target or not prediction:
            continue
        rows_for_metrics.append(make_oracle_row(sample, target, prediction, cv_path, planner))

    row_by_id = {row["sample_id"]: row for row in rows_for_metrics}
    for sample_id, case in selected_human_ids(args.human_summary, args.human_max_samples):
        sample = samples.get(sample_id)
        row = row_by_id.get(sample_id)
        if sample is None or row is None:
            continue
        source_id = sample.get("source", {}).get("source_id") or sample.get("metadata", {}).get("source_id")
        items.append(
            {
                **row,
                "block": "Human-action replay GT",
                "gt_source": "human-action replay-derived GT",
                "label": "defend_the_center",
                "case": case,
                "frame_path": resolve_frame_path(raw_dirs, sample["rgb_history_paths"][-1], source_id),
                "frame_paths": moving_frame_paths(sample, raw_dirs, source_id, len(row["target"])),
            }
        )
    metrics = summarize_rows(rows_for_metrics, "human_action_replay")
    return items, metrics


def scenario_name(sample: dict[str, Any]) -> str:
    metadata = sample.get("metadata", {})
    return str(metadata.get("scenario") or metadata.get("source_dataset") or "unknown")


def target_extent(target: list[list[float]]) -> float:
    return max((math.hypot(float(point[0]), float(point[1])) for point in target), default=0.0)


def classify_case(row: dict[str, Any]) -> str:
    if row["ours_ADE"] - row["cv_ADE"] > 80:
        return "Ours failure"
    if row["cv_ADE"] - row["ours_ADE"] > 80:
        return "CV-hard / Ours better"
    if max(row["cv_ADE"], row["ours_ADE"]) < 80:
        return "easy"
    return "mixed"


def choose_v4_rows(candidates: list[dict[str, Any]], max_samples: int) -> list[dict[str, Any]]:
    preferred = [
        "my_way_home",
        "rocket_basic",
        "basic",
        "health_gathering",
        "health_gathering_supreme",
        "deadly_corridor",
        "deathmatch",
        "multi_deathmatch",
        "predict_position",
        "defend_the_line",
        "defend_the_center",
    ]
    by_scenario: dict[str, list[dict[str, Any]]] = {}
    for row in candidates:
        by_scenario.setdefault(row["scenario"], []).append(row)

    selected: list[dict[str, Any]] = []
    for idx, scenario in enumerate(preferred):
        rows = by_scenario.get(scenario)
        if not rows:
            continue
        mode = idx % 3
        if mode == 0:
            key = lambda row: (row["cv_ADE"] - row["ours_ADE"], row["target_extent"])
        elif mode == 1:
            key = lambda row: (row["ours_ADE"] - row["cv_ADE"], row["target_extent"])
        else:
            key = lambda row: (-abs(row["ours_ADE"] - row["cv_ADE"]), -row["ours_ADE"])
        selected.append(max(rows, key=key))
        if len(selected) >= max_samples:
            return selected

    if len(selected) < max_samples:
        used = {row["sample_id"] for row in selected}
        remaining = sorted(candidates, key=lambda row: (row["target_extent"], row["cv_ADE"]), reverse=True)
        for row in remaining:
            if row["sample_id"] in used:
                continue
            selected.append(row)
            used.add(row["sample_id"])
            if len(selected) >= max_samples:
                break
    return selected[:max_samples]


def build_v4_items(args: argparse.Namespace, bases: list[Path]) -> tuple[list[dict[str, Any]], dict[str, Any]]:
    samples = {str(row["sample_id"]): row for row in read_jsonl(args.v4_dataset / "samples.jsonl")}
    test = split_ids(args.v4_dataset)
    ours = average_prediction_rows(args.v4_ours_predictions)
    oracle = {str(row["sample_id"]): row for row in read_jsonl(args.v4_oracle_predictions)}
    raw_dirs = load_raw_dirs(args.v4_dataset, bases)
    candidates: list[dict[str, Any]] = []

    for sample_id in sorted(test):
        sample = samples.get(sample_id)
        ours_row = ours.get(sample_id)
        oracle_row = oracle.get(sample_id)
        if sample is None or ours_row is None or oracle_row is None:
            continue
        target = oracle_row.get("target") or ours_row.get("target") or sample.get("future_local_path") or []
        prediction = ours_row.get("prediction") or []
        cv_path = oracle_row.get("constant_velocity_prediction") or ours_row.get("constant_velocity_prediction") or []
        pointnav_path = oracle_row.get("pointnav_goal_oracle_prediction") or []
        astar_path = oracle_row.get("astar_oracle_prediction") or []
        if not all([target, prediction, cv_path, pointnav_path, astar_path]):
            continue
        horizon = min(len(target), len(prediction), len(cv_path), len(pointnav_path), len(astar_path))
        target = target[:horizon]
        prediction = prediction[:horizon]
        cv_path = cv_path[:horizon]
        pointnav_path = pointnav_path[:horizon]
        astar_path = astar_path[:horizon]
        extent = target_extent(target)
        if extent < args.min_target_extent:
            continue
        cv_ade, cv_fde = path_error(cv_path, target)
        pointnav_ade, pointnav_fde = path_error(pointnav_path, target)
        astar_ade, astar_fde = path_error(astar_path, target)
        ours_ade, ours_fde = path_error(prediction, target)
        candidates.append(
            {
                "sample_id": sample_id,
                "sample": sample,
                "scenario": scenario_name(sample),
                "target_extent": extent,
                "target": target,
                "prediction": prediction,
                "cv": cv_path,
                "pointnav": pointnav_path,
                "astar": astar_path,
                "cv_ADE": float(oracle_row.get("constant_velocity_ADE", cv_ade)),
                "cv_FDE": float(oracle_row.get("constant_velocity_FDE", cv_fde)),
                "pointnav_ADE": float(oracle_row.get("pointnav_goal_oracle_ADE", pointnav_ade)),
                "pointnav_FDE": float(oracle_row.get("pointnav_goal_oracle_FDE", pointnav_fde)),
                "astar_ADE": float(oracle_row.get("astar_oracle_ADE", astar_ade)),
                "astar_FDE": float(oracle_row.get("astar_oracle_FDE", astar_fde)),
                "ours_ADE": float(ours_row.get("ADE", ours_ade)),
                "ours_FDE": float(ours_row.get("FDE", ours_fde)),
            }
        )

    selected = choose_v4_rows(candidates, args.v4_max_samples)
    items = []
    for row in selected:
        sample = row["sample"]
        source_id = sample.get("source", {}).get("source_id") or sample.get("metadata", {}).get("source_id")
        items.append(
            {
                **{k: v for k, v in row.items() if k != "sample"},
                "block": "V4 multi-scenario GT",
                "gt_source": "recorded ViZDoom policy trajectory GT",
                "label": metadata_label(sample, row["scenario"]),
                "case": classify_case(row),
                "frame_path": resolve_frame_path(raw_dirs, sample["rgb_history_paths"][-1], source_id),
                "frame_paths": moving_frame_paths(sample, raw_dirs, source_id, len(row["target"])),
            }
        )
    metrics = summarize_rows(candidates, "v4_multi_scenario")
    return items, metrics


def summarize_rows(rows: list[dict[str, Any]], name: str) -> dict[str, Any]:
    return {
        "name": name,
        "samples": len(rows),
        "constant_velocity": {"ADE": metric_mean(rows, "cv_ADE"), "FDE": metric_mean(rows, "cv_FDE")},
        "pointnav_goal_oracle": {"ADE": metric_mean(rows, "pointnav_ADE"), "FDE": metric_mean(rows, "pointnav_FDE")},
        "astar_oracle": {"ADE": metric_mean(rows, "astar_ADE"), "FDE": metric_mean(rows, "astar_FDE")},
        "ours": {"ADE": metric_mean(rows, "ours_ADE"), "FDE": metric_mean(rows, "ours_FDE")},
    }


def draw_column(
    canvas: Image.Image,
    x: int,
    y: int,
    w: int,
    h: int,
    title: str,
    subtitle: str,
    rgb: Image.Image,
    path: list[list[float]],
    full_path: list[list[float]],
    color: tuple[int, int, int],
    max_abs: float,
) -> None:
    draw = ImageDraw.Draw(canvas)
    draw.rounded_rectangle((x, y, x + w, y + h), radius=10, fill="white", outline=(216, 220, 226), width=2)
    draw.text((x + 16, y + 14), title, fill=color, font=font(27, bold=True))
    draw.text((x + 16, y + 50), wrap(subtitle, 38), fill=MUTED_COLOR, font=font(15))
    frame_box = (x + 16, y + 94, x + w - 16, y + 382)
    paste_center(canvas, rgb, frame_box)
    plot = draw_path_plot(path, (w - 32, h - 430), color, max_abs, full_path)
    canvas.paste(plot, (x + 16, y + 406))


def render_item_frame(
    item: dict[str, Any],
    order: int,
    total: int,
    progress: int,
    frame_path: Path | None,
    width: int,
    height: int,
) -> Image.Image:
    canvas = Image.new("RGB", (width, height), BG_COLOR)
    draw = ImageDraw.Draw(canvas)
    block_color = HUMAN_BLOCK_COLOR if item["block"].startswith("Human") else V4_BLOCK_COLOR
    header = f"{order:02d}/{total:02d}  {item['block']} / {item['label']} / {item['case']}"
    draw.text((38, 24), header, fill=TEXT_COLOR, font=font(34, bold=True))
    horizon = max(len(item["target"]), len(item["prediction"]), len(item["cv"]), len(item["pointnav"]), len(item["astar"]))
    metrics = (
        f"sample={item['sample_id']}    t={min(progress + 1, horizon):02d}/{horizon:02d}    "
        f"CV {item['cv_ADE']:.1f}/{item['cv_FDE']:.1f}    "
        f"PointNav {item['pointnav_ADE']:.1f}/{item['pointnav_FDE']:.1f}    "
        f"A* {item['astar_ADE']:.1f}/{item['astar_FDE']:.1f}    "
        f"Ours {item['ours_ADE']:.1f}/{item['ours_FDE']:.1f}"
    )
    draw.text((38, 70), wrap(metrics, 190), fill=MUTED_COLOR, font=font(18))
    warning = (
        f"GT source: {item['gt_source']}. "
        "PointNav/A* are privileged upper bounds using the GT endpoint; Ours uses RGB history + ego-motion only."
    )
    draw.text((38, 108), wrap(warning, 190), fill=block_color, font=font(17, bold=True))

    col_gap = 14
    margin_x = 34
    top = 154
    col_w = (width - 2 * margin_x - 4 * col_gap) // 5
    col_h = height - top - 34
    rgb = load_rgb(frame_path, (col_w - 36, 288))
    max_abs = axis_scale(item["cv"], item["pointnav"], item["astar"], item["target"], item["prediction"])
    shown = progress + 1
    specs = [
        ("CV", "recent motion only", "cv", CV_COLOR),
        ("PointNav", "GT endpoint oracle", "pointnav", POINTNAV_COLOR),
        ("A*", "pose graph + endpoint oracle", "astar", ASTAR_COLOR),
        ("GT", "future path label", "target", GT_COLOR),
        ("Ours", "RGB history + ego-motion", "prediction", PRED_COLOR),
    ]
    for idx, (title, subtitle, key, color) in enumerate(specs):
        x = margin_x + idx * (col_w + col_gap)
        draw_column(
            canvas,
            x,
            top,
            col_w,
            col_h,
            title,
            subtitle,
            rgb,
            clipped_path(item[key], shown),
            item[key],
            color,
            max_abs,
        )
    return canvas


def write_video(items: list[dict[str, Any]], args: argparse.Namespace) -> None:
    args.output.parent.mkdir(parents=True, exist_ok=True)
    writer = cv2.VideoWriter(str(args.output), cv2.VideoWriter_fourcc(*"mp4v"), args.fps, (args.width, args.height))
    if not writer.isOpened():
        raise RuntimeError(f"Could not open writer: {args.output}")
    try:
        total = len(items)
        for index, item in enumerate(items, start=1):
            frame_paths = item["frame_paths"] or [item["frame_path"]]
            if args.max_frames_per_item > 0:
                frame_paths = frame_paths[: args.max_frames_per_item]
            last_frame_bgr: np.ndarray | None = None
            for progress, frame_path in enumerate(frame_paths):
                frame = render_item_frame(item, index, total, progress, frame_path, args.width, args.height)
                last_frame_bgr = cv2.cvtColor(np.asarray(frame), cv2.COLOR_RGB2BGR)
                writer.write(last_frame_bgr)
            if last_frame_bgr is not None:
                for _ in range(max(0, args.hold_last_frames)):
                    writer.write(last_frame_bgr)
    finally:
        writer.release()


def write_poster(video_path: Path) -> Path:
    cap = cv2.VideoCapture(str(video_path))
    frames = int(cap.get(cv2.CAP_PROP_FRAME_COUNT))
    cap.set(cv2.CAP_PROP_POS_FRAMES, max(0, frames // 2))
    ok, frame = cap.read()
    cap.release()
    if not ok:
        raise RuntimeError(f"Could not read poster frame from {video_path}")
    poster = video_path.with_suffix(".png")
    cv2.imwrite(str(poster), frame)
    return poster


def write_reports(args: argparse.Namespace, items: list[dict[str, Any]], metrics: dict[str, Any], manifest: dict[str, Any]) -> None:
    args.report_dir.mkdir(parents=True, exist_ok=True)
    (args.report_dir / "metrics.json").write_text(json.dumps(metrics, indent=2), encoding="utf-8")
    (args.report_dir / "selection.json").write_text(json.dumps({"items": manifest["items"]}, indent=2), encoding="utf-8")
    lines = [
        "# Main 5-Baseline Multi-Scenario Video (5s)",
        "",
        "- Columns: CV, PointNav oracle, A* oracle, GT, Ours.",
        "- Human block GT: human-action replay-derived trajectory.",
        "- V4 block GT: recorded WIT-VZ ViZDoom policy trajectory.",
        "- PointNav and A* are privileged upper-bound baselines using the GT endpoint.",
        "- Xu-style and Khaleque-style proxies are intentionally excluded from this main video.",
        f"- V4 aggregate metrics use samples with target extent >= {args.min_target_extent:.1f}.",
        "",
        "## Metrics",
        "",
    ]
    for block_key, block in metrics["blocks"].items():
        lines.append(f"### {block_key}")
        lines.append("")
        lines.append(f"- Samples evaluated: {block['samples']}")
        lines.append("")
        lines.append("| method | ADE | FDE |")
        lines.append("|---|---:|---:|")
        for label, key in [
            ("CV", "constant_velocity"),
            ("PointNav oracle", "pointnav_goal_oracle"),
            ("A* oracle", "astar_oracle"),
            ("Ours", "ours"),
        ]:
            row = block[key]
            lines.append(f"| {label} | {row['ADE']:.2f} | {row['FDE']:.2f} |")
        lines.append("")
    lines.extend(["## Video Sequence", "", "| order | block | label | case | sample_id | Ours ADE | CV ADE |", "|---:|---|---|---|---|---:|---:|"])
    for idx, item in enumerate(items, start=1):
        lines.append(
            f"| {idx} | {item['block']} | {item['label']} | {item['case']} | `{item['sample_id']}` | "
            f"{item['ours_ADE']:.2f} | {item['cv_ADE']:.2f} |"
        )
    (args.report_dir / "summary.md").write_text("\n".join(lines) + "\n", encoding="utf-8")


def main() -> None:
    args = parse_args()
    bases = [ROOT, *[Path(item) for item in args.raw_root_base]]
    human_items, human_metrics = build_human_items(args, bases)
    v4_items, v4_metrics = build_v4_items(args, bases)
    items = human_items + v4_items
    if not items:
        raise RuntimeError("No renderable items found.")

    write_video(items, args)
    poster = write_poster(args.output)
    moving_frames = sum(
        min(len(item["frame_paths"]), args.max_frames_per_item) if args.max_frames_per_item > 0 else len(item["frame_paths"])
        for item in items
    )
    missing = sum(1 for item in items for path in item["frame_paths"] if path is None or not path.exists())
    manifest = {
        "output": str(args.output),
        "poster": str(poster),
        "mode": "main_5baseline_multiscenario_05s",
        "columns": ["CV", "PointNav", "A*", "GT", "Ours"],
        "fps": args.fps,
        "moving_frames": moving_frames,
        "missing_frame_count": missing,
        "items": [
            {
                "sample_id": item["sample_id"],
                "block": item["block"],
                "gt_source": item["gt_source"],
                "label": item["label"],
                "case": item["case"],
                "frames_rendered": (
                    min(len(item["frame_paths"]), args.max_frames_per_item)
                    if args.max_frames_per_item > 0
                    else len(item["frame_paths"])
                ),
                "cv_ADE": item["cv_ADE"],
                "pointnav_ADE": item["pointnav_ADE"],
                "astar_ADE": item["astar_ADE"],
                "ours_ADE": item["ours_ADE"],
            }
            for item in items
        ],
    }
    metrics = {
        "video": str(args.output),
        "gt_boundary": {
            "human_action_replay": "Human action labels are replayed in ViZDoom to derive the GT path.",
            "v4_multi_scenario": "GT is the recorded WIT-VZ ViZDoom trajectory, not human-play GT.",
        },
        "baseline_boundary": "PointNav and A* are privileged upper bounds using the GT endpoint.",
        "blocks": {
            "human_action_replay": human_metrics,
            "v4_multi_scenario": v4_metrics,
        },
    }
    args.output.with_suffix(".json").write_text(json.dumps(manifest, indent=2), encoding="utf-8")
    write_reports(args, items, metrics, manifest)
    print(json.dumps({"output": str(args.output), "poster": str(poster), "items": len(items), "missing_frame_count": missing}, indent=2))


if __name__ == "__main__":
    main()
